module.exports = {
    GETALL_ERROR: "Some error occured when retrieving user",
    ACTIVATE_SUCCESS: "Activated successfully",
    ACTIVATE_FAIL: "Can not found user with id = ",
    ACTIVATE_ERROR: "Some error occured when activate user",
    DEACTIVATE_SUCCESS: "Deactivated successfully",
    DEACTIVATE_FAIL: "Can not found user with id = ",
    DEACTIVATE_ERROR: "Some error occured when deactivate user",
    REMOVE_SUCCESS: "Deleted successfully",
    REMOVE_FAIL: "Can not found user with id = ",
    REMOVE_ERROR: "Some error occured when delete user",
    UPDATE_SUCCESS: "Updated successfully",
    UPDATE_FAIL: "Can not update user with id = ",
    UPDATE_ERROR: "Some error occured when update user",
    CHANGE_PWD_SUCCESS: "Change password successfully",
    CHANGE_PWD_FAIL: "Can not change password of user with id = ",
    CHANGE_PWD_ERR: "Some error occured when change password of user",
    PASSWORD_WRONG: "Please check password",

}